server:
  port: 80

build.name: @project.name@
build.version: @project.version@


spring:
  datasource:
    url: jdbc:mysql://abctech.cakjww6trexp.us-east-1.rds.amazonaws.com:3306/abctech
    username: admin
    password: Fiap1234
  jpa:
    hibernate:
      ddl-auto: none

